Repository Arthur-Aillet/Apollo, pull requests merged in 2023-10, with the labels that each got.

#15 chore: updated stack packages to project, created makefile
  .gitignore
  CHANGELOG.md
  Makefile
  README.md
  apollo.cabal
  app/Main.hs
  package.yaml
  src/Parser.hs
  src/Parser/Lib.hs
Labels: chore

#18 feat: unit tests and github actions
  .github/workflows/protect-pull-requests.yml
  package.yaml
  test/ParserSpec.hs
  test/Spec.hs
Labels: enhancement

#16 feat: Apollo vertical slice exemple
  app/Main.hs
  package.yaml
  src/Ast/Type.hs
  src/Eval.hs
  src/Eval/Builtin.hs
  src/Eval/Exec.hs
  src/Parser.hs
  src/Parser/Ast.hs
  src/Parser/Bool.hs
  src/Parser/Char.hs
  src/Parser/Condition.hs
  src/Parser/Error.hs
  src/Parser/Lib.hs
  src/Parser/Position.hs
  src/Parser/Symbol.hs
  src/Parser/Syntax.hs
  src/Parser/Type.hs
Labels: waiting

#19 fix: import error of parserAst in Condition.hs
  src/Parser/Condition.hs
Labels: bug

#26 feat: Compilation v1
  app/Main.hs
  doc/doc.bnf
  src/Ast/Compile.hs
  src/Ast/Context.hs
  src/Ast/Operable.hs
  src/Ast/Type.hs
  src/Ast/Utils.hs
  src/Eval.hs
  src/Eval/Atom.hs
  src/Eval/Builtin.hs
  src/Eval/Exec.hs
  src/Eval/Instructions.hs
  src/Eval/Operator.hs
  src/Parser.hs
  src/Parser/Ast.hs
  src/Parser/Char.hs
  src/Parser/Condition.hs
  src/Parser/Error.hs
  src/Parser/Symbol.hs
  stack.yaml.lock
  test/AtomSpec.hs
  test/InstructionSpec.hs
  test/OperatorSpec.hs
  test/ParserSpec.hs
  test/Spec.hs
Labels: enhancement

#27 fix: call functions logic now actually recursive instead of just appending insts
  app/Main.hs
  src/Ast/Compile.hs
  src/Ast/Operable.hs
  src/Eval/Atom.hs
  src/Eval/Exec.hs
  src/Eval/Instructions.hs
  src/Eval/Operator.hs
  test/InstructionSpec.hs
Labels: bug

#28 feat: Multable Variables added to Compilation and Evaluation
  app/Main.hs
  src/Ast/Compile.hs
  src/Ast/Context.hs
  src/Ast/Operable.hs
  src/Ast/Type.hs
  src/Eval.hs
  src/Eval/Atom.hs
  src/Eval/Exec.hs
  src/Eval/Instructions.hs
  src/Eval/Operator.hs
  src/Parser.hs
  src/Parser/Ast.hs
  src/Parser/Condition.hs
  test/OperatorSpec.hs
Labels: enhancement

#29 feat(AST-VM): advanced operations in vm (Casts, While) and error management refactor in compilation
  app/Main.hs
  src/Ast/Compile.hs
  src/Ast/Context.hs
  src/Ast/Display.hs
  src/Ast/Error.hs
  src/Ast/Operable.hs
  src/Ast/Type.hs
  src/Ast/Utils.hs
  src/Eval/Exec.hs
  src/Eval/Instructions.hs
  src/Eval/Operator.hs
  src/Parser/Char.hs
  test/InstructionSpec.hs
Labels: enhancement

#31 feat: non blocking compilation errors and logical operators
  .github/workflows/protect-pull-requests.yml
  app/Main.hs
  doc/doc.bnf
  src/Ast/Compile.hs
  src/Ast/Context.hs
  src/Ast/Display.hs
  src/Ast/Error.hs
  src/Ast/Operable.hs
  src/Ast/Type.hs
  src/Eval/Exec.hs
  src/Eval/Operator.hs
  src/PreProcess.hs
  test/InstructionSpec.hs
  test/OperatorSpec.hs
Labels: enhancement

#33 doc(BNF): corrected mistakes in the bnf
  doc/doc.bnf
Labels: documentation
